// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Article struct {
	ID                      int64
	FeedID                  int64
	Title                   string
	Link                    string
	Published               *time.Time
	DateFound               *time.Time
	ArticleContent          string
	ScrapedHtml             string
	ClickableParagraphCount int64
	Summary                 string
	Read                    int64
	Starred                 int64
}

type Comment struct {
	ID                 int64
	ArticleID          int64
	RelatedParagraphID int64
	CommentText        string
	DateAdded          time.Time
}

type Feed struct {
	ID                     int64
	Url                    string
	Title                  string
	LastFetched            time.Time
	CssSelContainer        string
	CssSelStart            string
	CssSelStop             string
	HtmlExtractionStrategy string
}
