// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int64
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
}

type ArticleCache struct {
	ID                  int64
	Link                string
	ArticleContent      sql.NullString
	Created             *time.Time
	ArticleID           int64
	ClickableBlockCount int64
}

type Feed struct {
	ID                     int64
	Url                    string
	Title                  string
	LastFetched            time.Time
	CssSelContainer        sql.NullString
	CssSelStart            sql.NullString
	CssSelStop             sql.NullString
	HtmlExtractionStrategy sql.NullString
}

type MarginNote struct {
	ID                      int64
	ArticleID               int64
	RelatedClickableBlockID int64
	Note                    string
	DateAdded               time.Time
}
