// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const insertArticleAnnotation = `-- name: InsertArticleAnnotation :exec
INSERT INTO annotations (article_id, start_data, end_data, note, snippet, date_added) 
VALUES (?,?,?,?,?, CURRENT_TIMESTAMP)
`

type InsertArticleAnnotationParams struct {
	ArticleID int64
	StartData string
	EndData   string
	Note      string
	Snippet   string
}

func (q *Queries) InsertArticleAnnotation(ctx context.Context, arg InsertArticleAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertArticleAnnotation,
		arg.ArticleID,
		arg.StartData,
		arg.EndData,
		arg.Note,
		arg.Snippet,
	)
	return err
}

const insertCachedArticle = `-- name: InsertCachedArticle :exec
INSERT INTO article_cache (
	article_id,
	link, 
	article_content, 
	created
) VALUES(
?,
?,
?, 
CURRENT_TIMESTAMP
)
`

type InsertCachedArticleParams struct {
	ArticleID      int64
	Link           string
	ArticleContent sql.NullString
}

func (q *Queries) InsertCachedArticle(ctx context.Context, arg InsertCachedArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertCachedArticle, arg.ArticleID, arg.Link, arg.ArticleContent)
	return err
}

const insertOrIgnoreArticle = `-- name: InsertOrIgnoreArticle :exec
INSERT OR IGNORE INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	date_found,
	summary, 
	read, 
	starred
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?,
	 ?, 
	 ?, 
	 ?
 )
`

type InsertOrIgnoreArticleParams struct {
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
}

func (q *Queries) InsertOrIgnoreArticle(ctx context.Context, arg InsertOrIgnoreArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertOrIgnoreArticle,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.DateFound,
		arg.Summary,
		arg.Read,
		arg.Starred,
	)
	return err
}

const selectAllFeeds = `-- name: SelectAllFeeds :many
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy from feeds
`

func (q *Queries) SelectAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, selectAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.LastFetched,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleAnnotationsByID = `-- name: SelectArticleAnnotationsByID :many
SELECT id, article_id, start_data, end_data, snippet, note, date_added FROM annotations WHERE article_id = ?
`

func (q *Queries) SelectArticleAnnotationsByID(ctx context.Context, articleID int64) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, selectArticleAnnotationsByID, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.StartData,
			&i.EndData,
			&i.Snippet,
			&i.Note,
			&i.DateAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleContentFromArticleCache = `-- name: SelectArticleContentFromArticleCache :one
SELECT article_content FROM article_cache WHERE article_id = ?
`

func (q *Queries) SelectArticleContentFromArticleCache(ctx context.Context, articleID int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, selectArticleContentFromArticleCache, articleID)
	var article_content sql.NullString
	err := row.Scan(&article_content)
	return article_content, err
}

const selectArticlesByFeedID = `-- name: SelectArticlesByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.date_found, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? 
ORDER BY COALESCE(a.published, a.date_found) DESC
`

type SelectArticlesByFeedIDRow struct {
	ID        int64
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
	FeedTitle string
}

func (q *Queries) SelectArticlesByFeedID(ctx context.Context, feedID int64) ([]SelectArticlesByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, selectArticlesByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectArticlesByFeedIDRow
	for rows.Next() {
		var i SelectArticlesByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.DateFound,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCachedArticleByLink = `-- name: SelectCachedArticleByLink :one
SELECT id, link, article_content, created, article_id FROM article_cache WHERE link = ?
`

func (q *Queries) SelectCachedArticleByLink(ctx context.Context, link string) (ArticleCache, error) {
	row := q.db.QueryRowContext(ctx, selectCachedArticleByLink, link)
	var i ArticleCache
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ArticleContent,
		&i.Created,
		&i.ArticleID,
	)
	return i, err
}

const selectFeedAndArticletByArticleID = `-- name: SelectFeedAndArticletByArticleID :one
SELECT 
	a.id as article_id,
	a.link as article_link, 
	a.title as article_title,
	a.starred as article_stars,
	a.published as article_published,
	f.id as feed_id, 
	f.title as feed_title,
	f.url as feed_url,
	f.css_sel_container as feed_css_sel_container, 
	f.css_sel_start as feed_css_sel_start, 
	f.css_sel_stop as feed_css_sel_stop, 
	f.html_extraction_strategy as feed_html_extraction_strategy   
FROM 
	articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id where a.id = ?
`

type SelectFeedAndArticletByArticleIDRow struct {
	ArticleID                  int64
	ArticleLink                string
	ArticleTitle               string
	ArticleStars               int64
	ArticlePublished           *time.Time
	FeedID                     int64
	FeedTitle                  string
	FeedUrl                    string
	FeedCssSelContainer        sql.NullString
	FeedCssSelStart            sql.NullString
	FeedCssSelStop             sql.NullString
	FeedHtmlExtractionStrategy sql.NullString
}

func (q *Queries) SelectFeedAndArticletByArticleID(ctx context.Context, id int64) (SelectFeedAndArticletByArticleIDRow, error) {
	row := q.db.QueryRowContext(ctx, selectFeedAndArticletByArticleID, id)
	var i SelectFeedAndArticletByArticleIDRow
	err := row.Scan(
		&i.ArticleID,
		&i.ArticleLink,
		&i.ArticleTitle,
		&i.ArticleStars,
		&i.ArticlePublished,
		&i.FeedID,
		&i.FeedTitle,
		&i.FeedUrl,
		&i.FeedCssSelContainer,
		&i.FeedCssSelStart,
		&i.FeedCssSelStop,
		&i.FeedHtmlExtractionStrategy,
	)
	return i, err
}

const selectFeedByID = `-- name: SelectFeedByID :one
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy FROM feeds where id = ?
`

func (q *Queries) SelectFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, selectFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const selectLatest5Articles = `-- name: SelectLatest5Articles :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.date_found, a.summary, a.read, a.starred, 
	f.title as feed_title 
 FROM articles a 
 INNER JOIN feeds f 
 ON f.id = a.feed_id 
 ORDER BY COALESCE(a.published, a.date_found) 
 DESC LIMIT 0, 5
`

type SelectLatest5ArticlesRow struct {
	ID        int64
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
	FeedTitle string
}

func (q *Queries) SelectLatest5Articles(ctx context.Context) ([]SelectLatest5ArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectLatest5Articles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectLatest5ArticlesRow
	for rows.Next() {
		var i SelectLatest5ArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.DateFound,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLatest5StarredArticles = `-- name: SelectLatest5StarredArticles :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.date_found, a.summary, a.read, a.starred, 
	f.title as feed_title 
 FROM articles a 
 INNER JOIN feeds f 
 ON f.id = a.feed_id 
 WHERE a.starred > 0
 ORDER BY starred DESC, COALESCE(a.published, a.date_found) 
 DESC LIMIT 0, 5
`

type SelectLatest5StarredArticlesRow struct {
	ID        int64
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
	FeedTitle string
}

func (q *Queries) SelectLatest5StarredArticles(ctx context.Context) ([]SelectLatest5StarredArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectLatest5StarredArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectLatest5StarredArticlesRow
	for rows.Next() {
		var i SelectLatest5StarredArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.DateFound,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSideBarData = `-- name: SelectSideBarData :many
SELECT
	f.title AS feed_title,
	f.id AS feed_id,
	COUNT(a.id) AS total_articles,
	COUNT(CASE WHEN a.read <> 0 THEN 1 END) AS articles_read
FROM feeds f
LEFT JOIN articles a ON f.id = a.feed_id
GROUP BY f.id, f.title
ORDER BY feed_title ASC
`

type SelectSideBarDataRow struct {
	FeedTitle     string
	FeedID        int64
	TotalArticles int64
	ArticlesRead  int64
}

func (q *Queries) SelectSideBarData(ctx context.Context) ([]SelectSideBarDataRow, error) {
	rows, err := q.db.QueryContext(ctx, selectSideBarData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectSideBarDataRow
	for rows.Next() {
		var i SelectSideBarDataRow
		if err := rows.Scan(
			&i.FeedTitle,
			&i.FeedID,
			&i.TotalArticles,
			&i.ArticlesRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUnreadArticlesByFeedID = `-- name: SelectUnreadArticlesByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.date_found, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? AND a.read = 0
ORDER BY COALESCE(a.published, a.date_found) DESC
`

type SelectUnreadArticlesByFeedIDRow struct {
	ID        int64
	FeedID    int64
	Title     string
	Link      string
	Published *time.Time
	DateFound *time.Time
	Summary   string
	Read      int64
	Starred   int64
	FeedTitle string
}

func (q *Queries) SelectUnreadArticlesByFeedID(ctx context.Context, feedID int64) ([]SelectUnreadArticlesByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, selectUnreadArticlesByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUnreadArticlesByFeedIDRow
	for rows.Next() {
		var i SelectUnreadArticlesByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.DateFound,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleSetAsRead = `-- name: UpdateArticleSetAsRead :exec
UPDATE articles SET read = 1 WHERE id = ?
`

func (q *Queries) UpdateArticleSetAsRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateArticleSetAsRead, id)
	return err
}

const updateArticleSetStarredValue = `-- name: UpdateArticleSetStarredValue :exec
UPDATE articles SET starred = ? WHERE id = ?
`

type UpdateArticleSetStarredValueParams struct {
	Starred int64
	ID      int64
}

func (q *Queries) UpdateArticleSetStarredValue(ctx context.Context, arg UpdateArticleSetStarredValueParams) error {
	_, err := q.db.ExecContext(ctx, updateArticleSetStarredValue, arg.Starred, arg.ID)
	return err
}
