// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addToArticleCache = `-- name: AddToArticleCache :exec
INSERT INTO article_cache (
	link, 
	article_content, 
	created
) VALUES(
?,
?, 
CURRENT_TIMESTAMP
)
`

type AddToArticleCacheParams struct {
	Link           string
	ArticleContent sql.NullString
}

func (q *Queries) AddToArticleCache(ctx context.Context, arg AddToArticleCacheParams) error {
	_, err := q.db.ExecContext(ctx, addToArticleCache, arg.Link, arg.ArticleContent)
	return err
}

const addToArticles = `-- name: AddToArticles :exec
INSERT OR IGNORE INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	published_parsed, 
	summary, 
	read, 
	starred
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?
 )
`

type AddToArticlesParams struct {
	FeedID          int64
	Title           string
	Link            string
	Published       time.Time
	PublishedParsed string
	Summary         string
	Read            int64
	Starred         int64
}

func (q *Queries) AddToArticles(ctx context.Context, arg AddToArticlesParams) error {
	_, err := q.db.ExecContext(ctx, addToArticles,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.PublishedParsed,
		arg.Summary,
		arg.Read,
		arg.Starred,
	)
	return err
}

const getArticlesByFeedID = `-- name: GetArticlesByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? 
ORDER BY a.published_parsed DESC
`

type GetArticlesByFeedIDRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       time.Time
	PublishedParsed string
	Summary         string
	Read            int64
	Starred         int64
	FeedTitle       string
}

func (q *Queries) GetArticlesByFeedID(ctx context.Context, feedID int64) ([]GetArticlesByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesByFeedIDRow
	for rows.Next() {
		var i GetArticlesByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedByLink = `-- name: GetCachedByLink :one
SELECT id, link, article_content, created FROM article_cache WHERE link = ?
`

func (q *Queries) GetCachedByLink(ctx context.Context, link string) (ArticleCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedByLink, link)
	var i ArticleCache
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ArticleContent,
		&i.Created,
	)
	return i, err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy FROM feeds where id = ?
`

func (q *Queries) GetFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const getFeedDataForArticleByArticleID = `-- name: GetFeedDataForArticleByArticleID :one
SELECT 
	a.id,
	a.link, 
	a.title,
	a.starred,
	f.id as feed_id, 
	f.title as feed_title,
	f.url as feed_url,
	f.css_sel_container, 
	f.css_sel_start, 
	f.css_sel_stop, 
	f.html_extraction_strategy   
FROM 
	articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id where a.id = ?
`

type GetFeedDataForArticleByArticleIDRow struct {
	ID                     int64
	Link                   string
	Title                  string
	Starred                int64
	FeedID                 int64
	FeedTitle              string
	FeedUrl                string
	CssSelContainer        sql.NullString
	CssSelStart            sql.NullString
	CssSelStop             sql.NullString
	HtmlExtractionStrategy sql.NullString
}

func (q *Queries) GetFeedDataForArticleByArticleID(ctx context.Context, id int64) (GetFeedDataForArticleByArticleIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedDataForArticleByArticleID, id)
	var i GetFeedDataForArticleByArticleIDRow
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.Title,
		&i.Starred,
		&i.FeedID,
		&i.FeedTitle,
		&i.FeedUrl,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy from feeds
`

func (q *Queries) GetFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.LastFetched,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatest5Articles = `-- name: GetLatest5Articles :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
 FROM articles a 
 INNER JOIN feeds f 
 ON f.id = a.feed_id 
 ORDER BY published 
 DESC LIMIT 0, 5
`

type GetLatest5ArticlesRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       time.Time
	PublishedParsed string
	Summary         string
	Read            int64
	Starred         int64
	FeedTitle       string
}

func (q *Queries) GetLatest5Articles(ctx context.Context) ([]GetLatest5ArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatest5Articles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatest5ArticlesRow
	for rows.Next() {
		var i GetLatest5ArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSidebarData = `-- name: GetSidebarData :many
SELECT
	f.title AS feed_title,
	f.id AS feed_id,
	COUNT(a.id) AS total_articles,
	COUNT(CASE WHEN a.read <> 0 THEN 1 END) AS articles_read
FROM feeds f
LEFT JOIN articles a ON f.id = a.feed_id
GROUP BY f.id, f.title
ORDER BY feed_title ASC
`

type GetSidebarDataRow struct {
	FeedTitle     string
	FeedID        int64
	TotalArticles int64
	ArticlesRead  int64
}

func (q *Queries) GetSidebarData(ctx context.Context) ([]GetSidebarDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getSidebarData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSidebarDataRow
	for rows.Next() {
		var i GetSidebarDataRow
		if err := rows.Scan(
			&i.FeedTitle,
			&i.FeedID,
			&i.TotalArticles,
			&i.ArticlesRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadByFeedID = `-- name: GetUnreadByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? AND a.read = 0
ORDER BY a.published_parsed DESC
`

type GetUnreadByFeedIDRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       time.Time
	PublishedParsed string
	Summary         string
	Read            int64
	Starred         int64
	FeedTitle       string
}

func (q *Queries) GetUnreadByFeedID(ctx context.Context, feedID int64) ([]GetUnreadByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadByFeedIDRow
	for rows.Next() {
		var i GetUnreadByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleAsRead = `-- name: SetArticleAsRead :exec
UPDATE articles SET read = 1 WHERE id = ?
`

func (q *Queries) SetArticleAsRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setArticleAsRead, id)
	return err
}

const setArticleStarredValue = `-- name: SetArticleStarredValue :exec
UPDATE articles SET starred = ? WHERE id = ?
`

type SetArticleStarredValueParams struct {
	Starred int64
	ID      int64
}

func (q *Queries) SetArticleStarredValue(ctx context.Context, arg SetArticleStarredValueParams) error {
	_, err := q.db.ExecContext(ctx, setArticleStarredValue, arg.Starred, arg.ID)
	return err
}
