// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addToArticleCache = `-- name: AddToArticleCache :exec
INSERT INTO article_cache (
	link, 
	article_content, 
	created
) VALUES(
?,
?, 
CURRENT_TIMESTAMP
)
`

type AddToArticleCacheParams struct {
	Link           string
	ArticleContent sql.NullString
}

func (q *Queries) AddToArticleCache(ctx context.Context, arg AddToArticleCacheParams) error {
	_, err := q.db.ExecContext(ctx, addToArticleCache, arg.Link, arg.ArticleContent)
	return err
}

const addToArticles = `-- name: AddToArticles :exec
INSERT OR IGNORE INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	published_parsed, 
	updated, 
	updated_parsed, 
	summary, 
	read, 
	starred
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?
 )
`

type AddToArticlesParams struct {
	FeedID          int64
	Title           string
	Link            string
	Published       sql.NullTime
	PublishedParsed string
	Updated         sql.NullTime
	UpdatedParsed   string
	Summary         sql.NullString
	Read            sql.NullInt64
	Starred         sql.NullInt64
}

func (q *Queries) AddToArticles(ctx context.Context, arg AddToArticlesParams) error {
	_, err := q.db.ExecContext(ctx, addToArticles,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.PublishedParsed,
		arg.Updated,
		arg.UpdatedParsed,
		arg.Summary,
		arg.Read,
		arg.Starred,
	)
	return err
}

const getAllFromFeed = `-- name: GetAllFromFeed :many
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy from feeds
`

func (q *Queries) GetAllFromFeed(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFromFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.LastFetched,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFromFeedByID = `-- name: GetAllFromFeedByID :one
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy FROM feeds where id = ?
`

func (q *Queries) GetAllFromFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getAllFromFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const getArticlesByFeedID = `-- name: GetArticlesByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.updated, a.updated_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? 
ORDER BY a.published_parsed DESC
`

type GetArticlesByFeedIDRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       sql.NullTime
	PublishedParsed string
	Updated         sql.NullTime
	UpdatedParsed   string
	Summary         sql.NullString
	Read            sql.NullInt64
	Starred         sql.NullInt64
	FeedTitle       sql.NullString
}

func (q *Queries) GetArticlesByFeedID(ctx context.Context, feedID int64) ([]GetArticlesByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesByFeedIDRow
	for rows.Next() {
		var i GetArticlesByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Updated,
			&i.UpdatedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedByLink = `-- name: GetCachedByLink :one
SELECT id, link, article_content, created FROM article_cache WHERE link = ?
`

func (q *Queries) GetCachedByLink(ctx context.Context, link string) (ArticleCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedByLink, link)
	var i ArticleCache
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ArticleContent,
		&i.Created,
	)
	return i, err
}

const getOtherArticlesFromFeedByArticleID = `-- name: GetOtherArticlesFromFeedByArticleID :many
SELECT 
	a.id,
	a.link, 
	a.title,
	f.id as feed_id, 
	f.title as feed_title,
	f.url as feed_url,
	f.css_sel_container, 
	f.css_sel_start, 
	f.css_sel_stop, 
	f.html_extraction_strategy   
FROM 
	articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id where a.id = ?
`

type GetOtherArticlesFromFeedByArticleIDRow struct {
	ID                     int64
	Link                   string
	Title                  string
	FeedID                 int64
	FeedTitle              sql.NullString
	FeedUrl                string
	CssSelContainer        sql.NullString
	CssSelStart            sql.NullString
	CssSelStop             sql.NullString
	HtmlExtractionStrategy sql.NullString
}

func (q *Queries) GetOtherArticlesFromFeedByArticleID(ctx context.Context, id int64) ([]GetOtherArticlesFromFeedByArticleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOtherArticlesFromFeedByArticleID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOtherArticlesFromFeedByArticleIDRow
	for rows.Next() {
		var i GetOtherArticlesFromFeedByArticleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Title,
			&i.FeedID,
			&i.FeedTitle,
			&i.FeedUrl,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadByFeedID = `-- name: GetUnreadByFeedID :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.updated, a.updated_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
FROM articles a 
INNER JOIN feeds f 
ON f.id = a.feed_id 
WHERE feed_id = ? AND a.read = 0
ORDER BY a.published_parsed DESC
`

type GetUnreadByFeedIDRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       sql.NullTime
	PublishedParsed string
	Updated         sql.NullTime
	UpdatedParsed   string
	Summary         sql.NullString
	Read            sql.NullInt64
	Starred         sql.NullInt64
	FeedTitle       sql.NullString
}

func (q *Queries) GetUnreadByFeedID(ctx context.Context, feedID int64) ([]GetUnreadByFeedIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadByFeedID, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadByFeedIDRow
	for rows.Next() {
		var i GetUnreadByFeedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Updated,
			&i.UpdatedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latest5Articles = `-- name: Latest5Articles :many
SELECT 
	a.id, a.feed_id, a.title, a.link, a.published, a.published_parsed, a.updated, a.updated_parsed, a.summary, a.read, a.starred, 
	f.title as feed_title 
 FROM articles a 
 INNER JOIN feeds f 
 ON f.id = a.feed_id 
 ORDER BY published 
 DESC LIMIT 0, 5
`

type Latest5ArticlesRow struct {
	ID              int64
	FeedID          int64
	Title           string
	Link            string
	Published       sql.NullTime
	PublishedParsed string
	Updated         sql.NullTime
	UpdatedParsed   string
	Summary         sql.NullString
	Read            sql.NullInt64
	Starred         sql.NullInt64
	FeedTitle       sql.NullString
}

func (q *Queries) Latest5Articles(ctx context.Context) ([]Latest5ArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, latest5Articles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Latest5ArticlesRow
	for rows.Next() {
		var i Latest5ArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.PublishedParsed,
			&i.Updated,
			&i.UpdatedParsed,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
